package conversor.views;

import conversor.controllers.CurrencyController;

/**
 * Clase Vista AddCurrencyView.
 * 
 * Vista encargada de agregar monedas al sistema.
 * 
 * @author Luigi Salcedo
 */
public class AddCurrencyView extends javax.swing.JFrame {

    private ConversorApp parent;
    
    public AddCurrencyView(ConversorApp parent) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoLabel = new javax.swing.JLabel();
        codigoInput = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreInput = new javax.swing.JTextField();
        costoLabel = new javax.swing.JLabel();
        costoInput = new javax.swing.JTextField();
        agregarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        codigoLabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        codigoLabel.setText("Código (Ej: USD):");

        codigoInput.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        codigoInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombreLabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        nombreLabel.setText("Nombre (Ej: Peso):");

        nombreInput.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        nombreInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        costoLabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        costoLabel.setText("Costo de un USD:");

        costoInput.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        costoInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarButton.setBackground(new java.awt.Color(204, 255, 204));
        agregarButton.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        agregarButton.setText("Agregar moneda");
        agregarButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codigoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoInput))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreInput, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(costoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costoInput))
                    .addComponent(agregarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel)
                    .addComponent(codigoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        if(CurrencyController.addCurrency(costoInput.getText(), 
                                           nombreInput.getText(), 
                                           codigoInput.getText())
                )
        {
            parent.remakeOptions();
            this.dispose();
        }
    }//GEN-LAST:event_agregarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JTextField codigoInput;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField costoInput;
    private javax.swing.JLabel costoLabel;
    private javax.swing.JTextField nombreInput;
    private javax.swing.JLabel nombreLabel;
    // End of variables declaration//GEN-END:variables
}
