package conversor.views;

import conversor.controllers.CurrencyController;
import conversor.models.Currency;
import conversor.models.Exchanger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luigi Salcedo
 */
public class ConversorApp extends javax.swing.JFrame {

    public ConversorApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        remakeOptions();
    }
    
    public final void remakeOptions(){
        origenBox.removeAllItems();
        destinoBox.removeAllItems();
        for(Currency currency : Exchanger.getInstance().getCurrencies().values())
        {
            origenBox.addItem(currency.toString());
            destinoBox.addItem(currency.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        origenLabel = new javax.swing.JLabel();
        origenBox = new javax.swing.JComboBox<>();
        origenCantidadLabel = new javax.swing.JLabel();
        origenCantidadInput = new javax.swing.JTextField();
        separador = new javax.swing.JSeparator();
        destinoLabel = new javax.swing.JLabel();
        destinoBox = new javax.swing.JComboBox<>();
        destinoCantidadLabel = new javax.swing.JLabel();
        destinoResultadoLabel = new javax.swing.JLabel();
        convertirButton = new javax.swing.JButton();
        barraOpciones = new javax.swing.JMenuBar();
        opcionesOpcion = new javax.swing.JMenu();
        agregarOpcion = new javax.swing.JMenuItem();
        modificarOpcion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        origenLabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        origenLabel.setText("Moneda de origen:");

        origenBox.setBackground(new java.awt.Color(204, 204, 204));
        origenBox.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        origenBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        origenBox.setFocusable(false);
        origenBox.setLightWeightPopupEnabled(false);
        origenBox.setRequestFocusEnabled(false);
        origenBox.setVerifyInputWhenFocusTarget(false);

        origenCantidadLabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        origenCantidadLabel.setText("Cantidad de origen:");

        origenCantidadInput.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        origenCantidadInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        separador.setForeground(new java.awt.Color(51, 51, 51));

        destinoLabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        destinoLabel.setText("Moneda de destino:");

        destinoBox.setBackground(new java.awt.Color(204, 204, 204));
        destinoBox.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        destinoBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        destinoCantidadLabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        destinoCantidadLabel.setText("Cantidad de destino:");

        destinoResultadoLabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        destinoResultadoLabel.setText("Nada todavía");

        convertirButton.setBackground(new java.awt.Color(204, 255, 204));
        convertirButton.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        convertirButton.setText("Convertir");
        convertirButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        convertirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirButtonActionPerformed(evt);
            }
        });

        barraOpciones.setBackground(new java.awt.Color(204, 204, 204));
        barraOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        barraOpciones.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        opcionesOpcion.setText("Opciones");

        agregarOpcion.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        agregarOpcion.setText("Agregar moneda");
        agregarOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarOpcionActionPerformed(evt);
            }
        });
        opcionesOpcion.add(agregarOpcion);

        modificarOpcion.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        modificarOpcion.setText("Modificar moneda");
        modificarOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarOpcionActionPerformed(evt);
            }
        });
        opcionesOpcion.add(modificarOpcion);

        barraOpciones.add(opcionesOpcion);

        setJMenuBar(barraOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(separador)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(origenLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(origenBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(destinoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(destinoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(origenCantidadLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(origenCantidadInput)))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(destinoCantidadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinoResultadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(convertirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenLabel)
                    .addComponent(origenBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenCantidadLabel)
                    .addComponent(origenCantidadInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinoLabel)
                    .addComponent(destinoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinoCantidadLabel)
                    .addComponent(destinoResultadoLabel))
                .addGap(18, 18, 18)
                .addComponent(convertirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarOpcionActionPerformed
        AddCurrencyView acw = new AddCurrencyView(this); 
        acw.setVisible(true);
    }//GEN-LAST:event_agregarOpcionActionPerformed

    private void convertirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirButtonActionPerformed
        String origen;
        String destino;
        origen = (String)origenBox.getSelectedItem();
        origen = origen.split("-")[0].trim();
        
        destino = (String)destinoBox.getSelectedItem();
        destino = destino.split("-")[0].trim();
        
        float cantidad;
        try{
            String value = origenCantidadInput.getText();
            value = value.replace(",", ".");
            cantidad = Float.parseFloat(value);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, 
                    "El formato de la cantidad de origen no es valido.",
                    "Error formato de la cantidad.",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        destinoResultadoLabel.setText(CurrencyController.Convert(origen, 
                                    destino, cantidad));
    }//GEN-LAST:event_convertirButtonActionPerformed

    private void modificarOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarOpcionActionPerformed
        ModifyCurrencyView mcw = new ModifyCurrencyView(this);
        mcw.setVisible(true);
    }//GEN-LAST:event_modificarOpcionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregarOpcion;
    private javax.swing.JMenuBar barraOpciones;
    private javax.swing.JButton convertirButton;
    private javax.swing.JComboBox<String> destinoBox;
    private javax.swing.JLabel destinoCantidadLabel;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JLabel destinoResultadoLabel;
    private javax.swing.JMenuItem modificarOpcion;
    private javax.swing.JMenu opcionesOpcion;
    private javax.swing.JComboBox<String> origenBox;
    private javax.swing.JTextField origenCantidadInput;
    private javax.swing.JLabel origenCantidadLabel;
    private javax.swing.JLabel origenLabel;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
